// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo85gg8J8_SqCumv5qQFNLWQTLGNjLGcY',
    appId: '1:689120569757:web:6d9c8f627265dddab2e774',
    messagingSenderId: '689120569757',
    projectId: 'cinema-booking-1506d',
    authDomain: 'cinema-booking-1506d.firebaseapp.com',
    storageBucket: 'cinema-booking-1506d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMOLpR3IMhRwXo-EjcXQXaN85cwzpEMok',
    appId: '1:689120569757:android:1704c723759dc71bb2e774',
    messagingSenderId: '689120569757',
    projectId: 'cinema-booking-1506d',
    storageBucket: 'cinema-booking-1506d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATqqpGXe2Nn4oEzkAjIYbJ7ZBvMbgBsHs',
    appId: '1:689120569757:ios:f621aa752c23fa28b2e774',
    messagingSenderId: '689120569757',
    projectId: 'cinema-booking-1506d',
    storageBucket: 'cinema-booking-1506d.firebasestorage.app',
    iosBundleId: 'com.example.cinemaBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATqqpGXe2Nn4oEzkAjIYbJ7ZBvMbgBsHs',
    appId: '1:689120569757:ios:f621aa752c23fa28b2e774',
    messagingSenderId: '689120569757',
    projectId: 'cinema-booking-1506d',
    storageBucket: 'cinema-booking-1506d.firebasestorage.app',
    iosBundleId: 'com.example.cinemaBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo85gg8J8_SqCumv5qQFNLWQTLGNjLGcY',
    appId: '1:689120569757:web:26531cf240f46399b2e774',
    messagingSenderId: '689120569757',
    projectId: 'cinema-booking-1506d',
    authDomain: 'cinema-booking-1506d.firebaseapp.com',
    storageBucket: 'cinema-booking-1506d.firebasestorage.app',
  );
}
